git:
  commit:
    confirmOnQuitPlaceholder: false
  paging:
    colorArg: always
    pager: delta --paging=never
    # pager: delta --dark --paging=never
gui:
  skipNoStagedFilesAlert: true
  sidePanelWidth: 0.2 # gives you more space to show things side-by-side
